listening_addr: 127.0.0.1
listening_port: 8080
servers:
  - addr: 192.168.0.10
    healthcheck: /health
  - addr: 192.168.0.11
    healthcheck: /health
  - addr: 192.168.0.11
    healthcheck: /health-new